### ISSUE TITLE
Unable to open database file?

### ISSUE THREAD

**Issue by JL276** [shadowmoose/RedditDownloader#100]
RD was working fine before, but I am unsure what happened as now I get the following error:

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)`

I have tried uninstalling all packages(and redditdownloader itself) used and reinstalling it manually. I have also tried both python 3.7 and 3.8 with the same error. I have also tried running cmd prompt (including anaconda prompt) in administrative mode to no avail.

**Comment by shadowmoose** [comment]
Are you able to open the database file with a tool like https://sqlitebrowser.org/ ?

**Comment by JL276** [comment]
Where is the DB file?

**Comment by shadowmoose** [comment]
It should be the manifest file inside the target download directory.

**Comment by JL276** [comment]
Had to delete my settings.json file for it to work again.
