### ISSUE TITLE
Ability to download JUST saved posts or JUST liked posts

### ISSUE THREAD

**Issue by frankcharlton** [shadowmoose/RedditDownloader#105]
### Is your feature request related to a problem? Please describe.
I'm trying to archive both my likes and saves, but I use them for slightly different things, so want to separate them out.

### Describe the solution you'd like:
I think there are two ways to handle this - pass in a like/save parameter (which would run either one), or pass in a paramter to have both run, but get saved into a 'saves' and 'likes' folder respectively. 

### Additional context:
This tool is really awesome, and you should be proud of your work here. It's really a massive timesaver for archival.

**Comment by shadowmoose** [comment]
Hey, thanks for the suggestion. 

If you use the other source - "Submissions and Comments a Redditor has Upvoted or Saved" for yourself, you should be able to add a source for each type individually. The original default "Liked/Saved" source only really exists for legacy config reasons.
