### ISSUE TITLE
TypeError: argument of 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Pihg** [shadowmoose/RedditDownloader#109]
I get this error (in the title) after selecting "3: Don't auto-open a browser" during the initial setup when asking how I would like to open the UI. In my mind, I was hoping to simply get the server running then interact with it over the WebUI for configuration.

I have a unique use case: it runs headless on an unRAID server, and it DOES work if I manually configure it with the non-browser initial startup guide via the command line, but once I go to edit the settings.json file, and I set start_server to "true", I wrap back to the same error I had before.

Specifically, it spits the text as seen in the image attached. It's an identical error both when trying to select don't auto-open browser at initial install, and when I manually configure the settings and set server_start to be true. Seems to be tied to initiating the web server.

In my particular case, if I ever reboot the server, I need to reinstall the dependencies prior to running the main program, which doesn't bother me much as this thing rarely reboots. So I've rebooted several times to reinstall eel / eelwrapper, but it doesn't seem to repair it.

Hope this is enough context to help!
<img width="889" alt="Screen Shot 2020-01-14 at 11 13 46 PM" src="https://user-images.githubusercontent.com/59909624/72413167-ff032280-3723-11ea-8145-f3bbb2b68be6.png">

**Comment by shadowmoose** [comment]
Thanks for the detailed report. It seems like I may have missed a config option when I wrote the browser startup logic.

I'll fix this soon. I'm expecting to roll out a patch (3.0.1) in the next day or so, after I round up any bugs that come in from the 3.0.0 release.

**Comment by Pihg** [comment]
Awesome! I’m glad you found the writeup helpful. Seems you already worked it a bit - I’ll give it a shot when I can. Thanks!

**Comment by shadowmoose** [comment]
Should be fixed as of [Release 3.0.1](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.1). Feel free to let me know if you run into any more issues.

**Comment by Pihg** [comment]
Yup! 3.0.1 fixed it. Thanks a ton, for the patch and the program in the first place!
