### ISSUE TITLE
TypeError: missing 2 positional arguments

### ISSUE THREAD

**Issue by Pihg** [shadowmoose/RedditDownloader#112]
### Describe the bug
Hi again!

When using RMD's browser to search and display downloaded content, items known to exist turn no results, and in the command line I get the following:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "site-packages/eel/__init__.py", line 251, in _process_message
TypeError: api_search_posts() missing 2 required positional arguments: 'page_size' and 'page'
2020-01-19T06:32:15Z <Greenlet at 0x1467df0c5dd0: _process_message({'call': 10.960289702619232, 'name': 'api_search_p, <geventwebsocket.websocket.WebSocket object at 0x1)> failed with TypeError

### Environment Info
- Tested under ubuntu 19.04 and unRAID 6.8.1 (still linux)
RMD 3.0.1

I've attached a screenshot of the exact CLI output.
<img width="888" alt="Screen Shot 2020-01-18 at 10 32 36 PM" src="https://user-images.githubusercontent.com/59909624/72676159-edcb5600-3a42-11ea-8300-8f0bc393ed1b.png">

I've tried pointing it into new/empty directories, and even though it's an empty directory I get the same error when I make a search. I ran the database upgrade script since I came from an earlier version and it seemed to run successfully, but I reckon that's not the issue since empty directories also produce the error.

**Comment by shadowmoose** [comment]
Hmm, interesting. Can you try reloading the UI by pressing ctrl+F5, and see if that works? It may be caused by a cached earlier UI version.

**Comment by Pihg** [comment]
DUDE! That's...extremely weird. That worked! I've tried different browsers and inside different VMs. But hey, it's working! I'll keep that in mind if I see it in the future. Thanks!

**Comment by shadowmoose** [comment]
Good to know, thanks for the feedback. I'll likely implement something to prevent caching in the next release.
