### ISSUE TITLE
Custom location for manifest.sqlite

### ISSUE THREAD

**Issue by sporez** [shadowmoose/RedditDownloader#123]
### Is your feature request related to a problem? Please describe.
I want to rip to a folder that is mounted with SMB however the manifest.sqlite database seems to get corrupted/locked for whatever reason. It doesn't seem to be a problem when downloading to a local folder.

### Describe the solution you'd like:
It would be nice to have a setting with the option to store the manifest.sqlite database in a custom location that is not the location that the content is being saved into, therefore avoiding the corruption issue in my case.

**Comment by pbo10** [comment]
I just had this same problem so would vote for this as well. 

It would be a nice simple solution if the database file either went in the same AppData folder as the settings file or you could select where you want it separately from the content.

**Comment by sporez** [comment]
So I'm late in replying but this is how I fixed the problem. I modified the code to add the option for a custom location for the manifest file.  This is what I changed:

Added this line into static/settings.py:
`add("output", Setting("db_dir", os.path.join(os.getcwd(), 'download'), desc="The base directory the db file resides in. Cannot contain tags."))`

Then in the ~/.local/share/RMD/settings.json file add this line under the "output" section:
`"db_dir": "/home/sporez/.local/share/RMD/",`

That will allow you to give it a custom location to store the manifest.  Haven't had any lock/corrupted issues since changing this.

**Comment by shadowmoose** [comment]
Hey, didn't give feedback on this earlier, but I've added this functionality to RMD. It isn't deployed currently, but the master branch has it as of ee67bade9a97659f7bb426ba72a4dfc073d05edf. 

It supports relative paths that will still map into the target download dir, but also allows absolute paths to fully customize where you want it saved.
