### ISSUE TITLE
multiple settings.json with windows.exe

### ISSUE THREAD

**Issue by AplhaSlayer1964** [shadowmoose/RedditDownloader#137]
Is it possible to use multiple settings.json files with the windows.exe? I'd like to set a second download directory for stuff I have saved while at the same time have a directory for user posts so they aren't all mixed together.

**Comment by shadowmoose** [comment]
This is only possible currently by passing in the `--settings=path/to/settings.json` command line argument. 

You can do this with the windows executable simply by opening the terminal in the same folder (Shift+right-click in the folder, and "Open Powershell here"), then running `./RMD-windows.exe --settings="<path here>"`.

If you're only looking to separate the download directories by type, however, I would look at [changing the output file_name_pattern setting](https://shadowmoose.github.io/RedditDownloader/Advanced_Usage/Settings/#file-name-patterns) to something like `/[type]/[subreddit]/[author] - [title]`. Doing this is more efficient than splitting RMD into two separate application launches.
