### ISSUE TITLE
What hosts are supported?

### ISSUE THREAD

**Issue by Pocochub** [shadowmoose/RedditDownloader#139]
For example imgur, gfycat, etc.

Are there any logs for links that were not able to be downloaded?

**Comment by shadowmoose** [comment]
There are custom handlers to support Imgur, Gyfcat, and Tumblr. Then there is a handler to (attempt) to support grabbing the "main" media from most blog or news sites. Finally, RMD uses YTDL to [support all these sites](https://ytdl-org.github.io/youtube-dl/supportedsites.html).

As for looking at failed downloads, you can click the "Failed Downloads" link on the home page of the WebUI. That will expand a list of all failed/incomplete posts.
