### ISSUE TITLE
macOS release asset downloads as text document

### ISSUE THREAD

**Issue by patel-jeel92** [shadowmoose/RedditDownloader#145]
### Describe the bug
When a user goes in and tries to download the macOS or Ubuntu asset, the downloaded file gets downloaded as a text document.

### Environment Info
 - **OS:** 
macOS
 - **RMD Version:**
3.1.0

**Comment by shadowmoose** [comment]
Hey, this looks like a duplicate issue. Please see [this comment](https://github.com/shadowmoose/RedditDownloader/issues/141#issuecomment-636171256), and try running it that way. I'll add documentation for this on the next release.
