### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by anup2050** [shadowmoose/RedditDownloader#146]
No matter what video post i download from any subreddit, It is broken in middle segment. Can someone help me please
![vlcsnap-00001](https://user-images.githubusercontent.com/66366537/83935213-2773e200-a7d5-11ea-8979-835b7a711d2b.png)

**Comment by anup2050** [comment]
so i just noticed that the post without audio is ok but the ones that have audio have this issue. anyone facing the same issue?

**Comment by shadowmoose** [comment]
Hey, as mentioned in your previous report, this is not a bug with RMD - this is a bug with either YTDL or FFMPEG. Sorry, but I cannot fix this problem on through RMD.
