### ISSUE TITLE
Error generating user agent on wizard.

### ISSUE THREAD

**Issue by will76** [shadowmoose/RedditDownloader#15]
I wasn't able to update through the app, so I deleted everything and downloaded again. 
Here's what I got:

`Traceback (most recent call last):
  File "main.py", line 175, in <module>
    p = Scraper(settings, custom_settings)
  File "main.py", line 66, in __init__
    self.settings = Settings(settings_file, can_save=(c_settings is None), can_load=(not args.test) )
  File "./classes\settings.py", line 42, in __init__
    wizard.run(file)
  File "./classes/wizards\wizard.py", line 70, in run
    "user_agent": "RMD-"+random.random(),
TypeError: must be str, not float`

**Comment by GreysenEvans** [comment]
I have the same problem. The wizard spits out this error after completing setup:
`Traceback (most recent call last):
  File "main.py", line 175, in <module>
    p = Scraper(settings, custom_settings)
  File "main.py", line 66, in __init__
    self.settings = Settings(settings_file, can_save=(c_settings is None), can_load=(not args.test) )
  File "./classes\settings.py", line 42, in __init__
    wizard.run(file)
  File "./classes/wizards\wizard.py", line 70, in run
    "user_agent": "RMD-"+random.random(),
TypeError: must be str, not float`

@will76, a temporary fix is to manually configure your settings in `INSTALL_FOLDER\settings.JSON`.
Just replace the default values for `client_id`, `client_secret`, `password`, and `username`. You can just make up a random number for `user_agent`. Don't delete the quotes.

**Comment by will76** [comment]
Yeah, I did that and forgot to mention here.
So there are two issues: Update from the app and Wizard not working properly.

**Comment by shadowmoose** [comment]
Sorry about the delay, didn't notice this issue had cropped up.

I see what the issue is (it's a type thing). I'm not sure how it slipped through, but I'll roll out a fix for it shortly.
