### ISSUE TITLE
How do uninstall RedditDownloader 

### ISSUE THREAD

**Issue by Millichrome** [shadowmoose/RedditDownloader#159]
I installed using the pre-built binary from here:

https://github.com/shadowmoose/RedditDownloader/releases/tag/3.1.1

I looked through the GitHub page, shadowmoose.github.io and the WebUI and I couldn't find an answer.

Doing a search did not give any useful results.

**Comment by shadowmoose** [comment]
RMD doesn't use an installer - it's contained within the binary. If you want the metadata it assembles gone as well, there will likely be a folder in your local user data folder. On windows, this is stored in the `%LOCALAPPDATA%` directory, under 'RedditDownloader'.
