### ISSUE TITLE
Pushshift error

### ISSUE THREAD

**Issue by leodomi** [shadowmoose/RedditDownloader#160]
Hi, the application loads for a while but does not download anything new. Looking at the CMD window, it displays this error line : 

![image](https://user-images.githubusercontent.com/33042520/87837071-9cd1d880-c892-11ea-8f8e-af83ca510880.png)

I'm using the latest version (3.1.1) on W10 but it shows up as 3.1.0.

**Comment by shadowmoose** [comment]
Strange, I'm not seeing this issue in testing, but it looks like their site is having intermittent issues. It's possible you're having connection issues - are you able to reach https://pushshift.io ?

**Comment by leodomi** [comment]
Indeed, when I go on the site I get a 522 error. But I checked with "https://downforeveryoneorjustme.com/pushshift.io" and apparently their site's down.

**Comment by shadowmoose** [comment]
I'm going to close this, because it is likely related to current internet issues. If this continues after you're able to access their site normally again, please reopen this issue.
