### ISSUE TITLE
Windows binary 3.1.1 still shows as 3.1.0 on GUI

### ISSUE THREAD

**Issue by chalupas** [shadowmoose/RedditDownloader#164]
### Describe the bug
I downloaded the windows binary from https://github.com/shadowmoose/RedditDownloader/releases/tag/3.1.1  yet it still shows the version as 3.1.0 on the home page of the GUI. 

### Environment Info
 - **OS:** Windows
 - **RMD Version:** 3.1.0

**Comment by shadowmoose** [comment]
Looks like I missed that one. I'll fix it in the next release.
