### ISSUE TITLE
Prebuild Release Binary just don't work

### ISSUE THREAD

**Issue by adinxu** [shadowmoose/RedditDownloader#177]
### Describe the bug
I use the Release 3.1.1 for windows, when I open this exe ，choose  'Chrome Application Mode', the window close, and there is nothing to happen. The browser don't open automatic.
### Environment Info
 - **OS:** Windows 10 20H2
 - **RMD Version:** 3.1.1

please help me find out what's going on ，thx very much~

**Comment by shadowmoose** [comment]
Hey, I'm working on some overhauls to RMD currently, which should fix this. In the meantime, please make sure you have Chrome installed if you're launching in app mode.

**Comment by adinxu** [comment]
Well, I've tried the first two options, but they all didn't work. I have Edge and Chorme on my computer.
 look forward to your new update~ 👍🏻
