### ISSUE TITLE
Can't access RMD over local network 

### ISSUE THREAD

**Issue by ShayanYaseen** [shadowmoose/RedditDownloader#178]
### Describe the bug
Cannot access the server over local network.
When running the program on a local server and trying to access the gui/web interface from a device on the same network.

### Environment Info
 - OS: Mac/Linux 
 - RMD Version: 3.10
- Firewall :turned off

### Screenshots/Information
Chrome error on accessing http:192.168.1.16:7505/index.html on mobile : ERR_CONNECTION_REFUSED

### Additional context
Running using the source code.
Server is accessible on the same device , Settings and setup (authentication) has been completed. I wanted to move the program to my home server and access from mobile . Other servers including a test node server are easily accessible.

**Comment by shadowmoose** [comment]
Strange, it should work just like any other server application. Which `host` are you using, in the settings?

**Comment by ShayanYaseen** [comment]
I read the documentation and found this entry 

```
host

    Description: The host to bind on.
    Expected Type: str
    Default value: localhost
```
Unfortunately i am not clear what to replace local-host with , I tried both "localhost" and my local ip address as the "Default value"

**Comment by ShayanYaseen** [comment]
Hey again,

I finally got around the problem now, after staring at the settings in the WebUI long enough i finally realized i needed to restart the server for the setting changes to take place.

Thanks and thanks for this wonderful piece of software you have created
