### ISSUE TITLE
[Feature] Argument to select specific 'source' to download

### ISSUE THREAD

**Issue by will76** [shadowmoose/RedditDownloader#18]
Either add an id to each 'source' on the json or the possibility to download the chosen one by alias
 
eg. python main.py -s 3 ( --source 3)
eg. python main.py -a "aww_pics" ( --alias "aww_pics")

Thanks a lot

**Comment by shadowmoose** [comment]
An argument to run only specified Sources from the existing settings file sounds like a good idea.

I'll roll it into the next update.
