### ISSUE TITLE
How to starting downloading videos?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [shadowmoose/RedditDownloader#183]
So sorry, this is my first time using RMD. I have downloaded and installed https://github.com/shadowmoose/RedditDownloader/releases/download/3.1.1/RMD-windows.exe on my windows 10. 
But I don't know how to starting download the videos.
I already set auth my accounts in the setting tab.  
For example, I would like to download videos from https://www.reddit.com/r/WhatsWrongWithYourDog/. Then I add a new source
![image](https://user-images.githubusercontent.com/36155295/102760648-2b560300-43b9-11eb-805e-c896b9d7bf25.png)

Then from the tab browser, I type dog but nothing showing.
![image](https://user-images.githubusercontent.com/36155295/102760773-61938280-43b9-11eb-88c0-95dc37828027.png)

Can anyone tell me how to do it?
And any video tutorial for using this tool?
Thank you so much!!

**Comment by shadowmoose** [comment]
Hey, you'll need to hit the "Start Downloading" button in the top right, if you haven't yet. If you've done that and you still don't see anything, RMD may not be able to find media.

**Comment by nguyenanhtuan1008** [comment]
> Hey, you'll need to hit the "Start Downloading" button in the top right, if you haven't yet. If you've done that and you still don't see anything, RMD may not be able to find media.

I mean RMD can not find media so I can't hit the "Start Downloading" button. I need the setting to show all the media first!

**Comment by xatnight** [comment]
> > Hey, you'll need to hit the "Start Downloading" button in the top right, if you haven't yet. If you've done that and you still don't see anything, RMD may not be able to find media.
> 
> I mean RMD can not find media so I can't hit the "Start Downloading" button. I need the setting to show all the media first!

Did you put the subreddit name in the settings? You need to put the name (only the name, not the link or anything) into this field.
![image](https://user-images.githubusercontent.com/57115057/103030939-1b772400-455d-11eb-97fe-12560968440d.png)

**Comment by nguyenanhtuan1008** [comment]
> > > Hey, you'll need to hit the "Start Downloading" button in the top right, if you haven't yet. If you've done that and you still don't see anything, RMD may not be able to find media.
> > 
> > 
> > I mean RMD can not find media so I can't hit the "Start Downloading" button. I need the setting to show all the media first!
> 
> Did you put the subreddit name in the settings? You need to put the name (only the name, not the link or anything) into this field.
> ![image](https://user-images.githubusercontent.com/57115057/103030939-1b772400-455d-11eb-97fe-12560968440d.png)

Thank you so much! I just did like you said. It's worked perfectly.
