### ISSUE TITLE
Stopped working after changing download directory

### ISSUE THREAD

**Issue by HentaiScenes** [shadowmoose/RedditDownloader#191]
### Describe the bug
I was trying to scrape a large sub and it wasn't downloading as much as i thought. (30 of probably 10k photos) so I changed the output directory and have been getting the attached error.

### Environment Info
 - **OS:** [e.g. Windows/Mac/Linux - include version if possible]
 - **RMD Version:** [e.g. "3.0.0" - run with "-v" to find this]

### Screenshots/Information
If applicable, add screenshots (or copies of error printouts) to help explain your problem.
[Include links to failed URLs/Posts, names of Sources, or other useful info here]
![image](https://user-images.githubusercontent.com/77706494/108583769-01ae4f00-730a-11eb-95f1-14f30860ad87.png)

### Additional context
[Add any other context about the problem here.]

**Comment by shadowmoose** [comment]
It seems like the manifest got corrupted somehow. If you're not storing too many things from RMD already, it's probably simplest to delete the manifest file and restart.

**Comment by HentaiScenes** [comment]
> It seems like the manifest got corrupted somehow. If you're not storing too many things from RMD already, it's probably simplest to delete the manifest file and restart.

I still get the same error after deleting the manifest. I am running the .exe file btw.
