### ISSUE TITLE
KeyError: 'u'

### ISSUE THREAD

**Issue by pbo10** [shadowmoose/RedditDownloader#193]
I've had a number of subreddits configured to download for a while and it's been working fine, but the last couple of days it runs and gets half way through and throws the error "KeyError: 'u'" and doesn't go any further, so it only downloads the first couple of subreddits in my list.

Unfortunately it doesn't give much information on exactly which part it's failing on. Is there a more detailed log file I can check somewhere?

### Environment Info
 - Windows 10 Pro
 - 3.1.3

### Screenshots/Information
![image](https://user-images.githubusercontent.com/18058415/109353705-a386ec00-7874-11eb-9a16-36a15ff69c93.png)

**Comment by shadowmoose** [comment]
Should be patched as of #194. I'll be rolling this out for the executables shortly.
