### ISSUE TITLE
Request: Sourcebased name pattern

### ISSUE THREAD

**Issue by T-prog3** [shadowmoose/RedditDownloader#210]
I prefer a Username/Subreddit/content structure when i download but this will endup in a hugh mess when i have two or more sources. So if i have organized my sources as: Art, Memes, Div... I will still have everything in the same folder and will not know what source each user belong to.

If we could use the source name as a name pattern it would solve this issue and allow us to organize in a more personal way like Art/Username/Subreddit/content, Memes/Username/Subreddit/content

**Comment by shadowmoose** [comment]
Hey, thanks for the suggestion. You actually can already do this in RMD, using the `source_alias` tag. See [here](https://shadowmoose.github.io/RedditDownloader/Advanced_Usage/Settings/#file-name-patterns) for more information.
