### ISSUE TITLE
Update exe process fails

### ISSUE THREAD

**Issue by phhowe17** [shadowmoose/RedditDownloader#238]
### Describe the bug
After downloading the current executable and launching, it attempts to check for a newer version.  This process fails with the following message:

Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Checking for a standalone release update for platform windows...
Hash mismatch! Time to update... 5282cd56b02e0bc5f8dffa395c7672a87db5ba14fd2b3762d71cba300d648784
Downloading update from URL: https://github.com/shadowmoose/RedditDownloader/releases/download/3.1.5/RMD-windows.exe
Moving existing executable to backup...
Error downloading update! The downloaded file is malformed, or does not match hashes! 5282cd56b02e0bc5f8dffa395c7672a87db5ba14fd2b3762d71cba300d648784
Unable to download update! Check https://raw.githubusercontent.com/shadowmoose/RedditDownloader/release-metadata-3.x/release.json for details!
Traceback (most recent call last):
  File "Run.py", line 163, in <module>
  File "Run.py", line 124, in check_standalone_update
RuntimeError: Unable to download update! Check https://raw.githubusercontent.com/shadowmoose/RedditDownloader/release-metadata-3.x/release.json for details!

Unable to download update! Please manually check the project: https://github.com/shadowmoose/RedditDownloader

### Environment Info
 - **OS:** Windows 11 21h2 22000.469
 - **RMD Version:** 3.1.5

### Screenshots/Information
See above

**Comment by nathanielhudson** [comment]
I am also experiencing this.

**Comment by casualdegenerate** [comment]
For me it's saying there is a hash mismatch, which is a bit scary since I've already ran it and it's saying that.

**Comment by shadowmoose** [comment]
Hey sorry, I've been away for quite a while as I've been too busy to work much on these open source projects. There appears to be an issue with RMD's automated build process right now. I'll look into it as soon as I can get the chance.

**Comment by shadowmoose** [comment]
Update: The build process should be working again. It turns out, that was a simpler fix that I thought. Feel free to reopen if you're still experiencing issues.
