### ISSUE TITLE
SyntaxError - OS X

### ISSUE THREAD

**Issue by lyndon-williams** [shadowmoose/RedditDownloader#24]
HI, I'm hitting a snag over here.

> "main.py", line 252
>     print( ("\t%3d:%-"+padding_len+"s -> ") % (i, name) , end='')
>                                                              ^
> SyntaxError: invalid syntax
> 

I'm running OS X 10.13.2, running python 2.7

Many thanks in advance for any assistance!

**Comment by shadowmoose** [comment]
Odd, from what I understand, that error could imply a malformed file. Are you sure that ```main.py``` has not been altered since downloading it? Perhaps try downloading it again.

If the issue persists, I may need a copy of the file to hunt this down.

**Comment by lyndon-williams** [comment]
I downloaded the zip file twice, and then unzipped it to two different locations. I've attached a copy of the file that I am using. Thanks for getting back to me so quickly!

[main.py.zip](https://github.com/shadowmoose/RedditDownloader/files/1952393/main.py.zip)

**Comment by shadowmoose** [comment]
Ah yes, I overlooked the version. You're probably running python 2.x, where RMD requires 3.4+ to run.

Try installing a more recent version of Python and giving that a go.

**Comment by lyndon-williams** [comment]
I just upgraded my man. I'll have a play! Thanks for following up.

**Comment by lyndon-williams** [comment]
I'm running Python 3.6.5 now and this is what I am getting when I try to execute...

> cd '/Users/wildfire/Desktop/RDL/RedditDownloader/' && '/usr/bin/pythonw'  '/Users/wildfire/Desktop/RDL/RedditDownloader/main.py'  && echo Exit status: $? && exit 1
> ________________________________________________________________________________
> | ~ @ Thundera (wildfire) 
> | => cd '/Users/wildfire/Desktop/RDL/RedditDownloader/' && '/usr/bin/pythonw'  '/Users/wildfire/Desktop/RDL/RedditDownloader/main.py'  && echo Exit status: $? && exit 1
> total 80
> -rwxr-xr-x@  1 wildfire  staff   380B 26 Apr 01:44 .coveragerc
> -rwxr-xr-x@  1 wildfire  staff   1.2K 26 Apr 01:44 .gitignore
> -rwxr-xr-x@  1 wildfire  staff   772B 26 Apr 01:44 .travis.yml
> -rwxr-xr-x@  1 wildfire  staff   3.4K 26 Apr 01:44 README.md
> -rwxr-xr-x@  1 wildfire  staff    48B 26 Apr 01:44 _config.yml
> drwxr-xr-x@ 11 wildfire  staff   352B 26 Apr 01:44 classes/
> drwxr-xr-x@  6 wildfire  staff   192B 26 Apr 01:44 docs/
> -rwxr-xr-x@  1 wildfire  staff   9.2K 26 Apr 01:44 main.py
> -rw-r--r--   1 wildfire  staff   3.9K 26 Apr 20:00 main.py.zip
> -rwxr-xr-x@  1 wildfire  staff    96B 26 Apr 01:44 requirements.txt
> drwxr-xr-x@ 10 wildfire  staff   320B 26 Apr 01:44 tests/
>   File "/Users/wildfire/Desktop/RDL/RedditDownloader/main.py", line 252
>     print( ("\t%3d:%-"+padding_len+"s -> ") % (i, name) , end='')
>                                                              ^
> SyntaxError: invalid syntax
> ________________________________________________________________________________
> | ~/Desktop/RDL/RedditDownloader @ Thundera (wildfire) 
> | =>

**Comment by shadowmoose** [comment]
Hey, interesting. Can you run a ```python -V``` command (or, I suppose, ```'/usr/bin/pythonw'  -V``` for you) - just to be sure it's using the newly-installed version?

The error line in question is still entirely valid in Python 3.

If the version isn't the issue, I'll have to find a way to do further testing on OS X.

**Comment by lyndon-williams** [comment]
It says this, but I know I am running 3.6.5 

> | ~/Desktop/RDL/RedditDownloader @ Thundera (wildfire) 
> | => python -V
> Python 2.7.10

Maybe it is an OS X issue?

**Comment by shadowmoose** [comment]
The command you are using is defaulting to python 2.7. You'll need to look up how to run the correct python version you have installed.
