### ISSUE TITLE
YTDL: ERROR: Unable to download JSON metadata: HTTP Error 502

### ISSUE THREAD

**Issue by thespikerman** [shadowmoose/RedditDownloader#240]
RMD is crashing when I get the error. Here is the output in the console:
-----------------------------------------------------------------------------------------------
Started downloader.
YTDL: ERROR: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. [URL]
C:\Users\*\AppData\Local\Temp\_MEI289962\psaw\PushshiftAPI.py:244: UserWarning: Not all PushShift shards are active. Query results may be incomplete
PushShift Warning: Unable to locate parent Submission: t3_soghbq
A WebUI just closed. Checking for other connections... (index.html)[1]
Open connections still exist. Not stopping UI server.
-----------------------------------------------------------------------------------------------

When this happens, RMD is still running, but the files trying to download/error won't clear the queue. shows "Status: Looking for video..."

youtube DL has been replaced by yt-dlp, is there a way we can manage what client is used, and can we also allow arguments to it so we can continue when hitting an error as well as set the yt-dlp output names?

**Comment by shadowmoose** [comment]
I'd like to support yt-dlp, but that would likely require extensive rewriting. The newer rewrite of RMD will be switching to dlp for the future, though.

In the meantime, I've unblocked a bug that was preventing the automatic updater from updating YTDL. This should hopefully fix your problem, assuming YTDL has fixed the site you're pulling from. Feel free to re-open if this is still an issue in the future.
