### ISSUE TITLE
No module named 'static'

### ISSUE THREAD

**Issue by bulvara** [shadowmoose/RedditDownloader#246]
I've installed RedditDownloader from git master. Out of ArchLinux habits I've copied the files to /usr/lib/python3.10/site-packages/redditdownloader since there was no _setup.py_. This error arises:

```
  File "/usr/lib/python3.10/site-packages/redditdownloader/__main__.py", line 6, in <module>
    import static.stringutil as su
ModuleNotFoundError: No module named 'static'
```

I've tried to install https://github.com/lukearno/static but this seems to be unrelated.

**Comment by shadowmoose** [comment]
Hey, you shouldn't need a static package, that's an import relative to the project. RMD is not a python package, and thus does not have a setup script. Please follow the installation steps here: https://shadowmoose.github.io/RedditDownloader/Getting_Started/Installing/
