### ISSUE TITLE
Grahical User Interface

### ISSUE THREAD

**Issue by Katie1995** [shadowmoose/RedditDownloader#25]
Would you consider making a grahical user interface for RMD?

**Comment by Katie1995** [comment]
Nice, looking forward to it. Keep up the good work!

**Comment by shadowmoose** [comment]
*I keep getting messaged about this, so have an update:*
I've begun the construction of a browser-based GUI.

It's nowhere near complete, but it's in progress at least. For those interested in following the work, [check it out at the **gui** branch.](https://github.com/shadowmoose/RedditDownloader/commits/gui)

It will be rolling out as the next big update, alongside the shift to a SQLite database & other performance improvements. I'll update this post again once I've got it further along.

**Comment by shadowmoose** [comment]
At long last, this is resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). 

Thanks for the suggestion.
