### ISSUE TITLE
Setting to change downloader

### ISSUE THREAD

**Issue by Knownish** [shadowmoose/RedditDownloader#277]
### Is your feature request related to a problem? Please describe.
yt-dlp can't download redgifs and gfycat videos

### Describe the solution you'd like:
an option to change the exe used for downloads

**Comment by Kazaflow** [comment]
I don't know how you would like to use a different exe for downloading as RMD is either just one standalone exe file, or the whole repo with all the python scripts. 
Anyway, I have a workaround for downloading from redgifs, I'm not sure if every step is necessary but I did it like this:
- First download the repo, as you can't change anything in the exe version.
- run '_pip uninstall youtube_dl_' and then install the same way '_yt-dlp_' (not sure if necessary)
- Now go inside your RMD folder, there in '_redditdownloader/processing/handlers_' you open '_ytdl.py_' in a text editor
- in the first line where it says '_import youtube_dl_' you change it to '_import yt_dlp as youtube_dl_' (not sure if necessary)
- then in line 48 you find **ydl_opts** which has that structure with 'something' : 'some value'
- within the ydl_opts you add "cookies" : "some path to a cookie file" with a comma at the end
- now you will actually need a cookie file from redgifs, there is a addon for that (on firefox theres "cookie.txt") which allows you to get the cookie as a txt which you can use for the ydl-opts cookie argument from before

Now again I don't know if I did a good job describing this "fix" or if it makes sense, but in my case it allowed me to download from redgifs with no issue.

**Comment by Knownish** [comment]
That seems to have worked, thanks!!!
