### ISSUE TITLE
Invalid client id.

### ISSUE THREAD

**Issue by Sn0wAlice** [shadowmoose/RedditDownloader#292]
### Describe the bug
When login:
![Capture d’écran 2023-07-13 à 20 11 08](https://github.com/shadowmoose/RedditDownloader/assets/38856824/f85a5cb5-268d-464d-851a-297ea793bfa9)

### Environment Info
 - **OS:** Mac
 - **RMD Version:** Reddit Media Downloader 3.1.5

### Screenshots/Information
Woking 2 weeks ago

none

**Comment by shadowmoose** [comment]
This is caused by the Reddit API changes, and unfortunately will not be fixed in the current state of the API.
