### ISSUE TITLE
Can't run the script at all

### ISSUE THREAD

**Issue by aliparlakci** [shadowmoose/RedditDownloader#37]
I did `pip install -r requirements.txt` but still get this:
```console
PS C:\Users\Ali\git\@shadowmoose\RedditDownloader> python .\main.py
Traceback (most recent call last):
  File ".\main.py", line 56, in <module>
    from classes.webserver import eelwrapper
  File "C:\Users\Ali\git\@shadowmoose\RedditDownloader\classes\webserver\eelwrapper.py", line 1, in <module>
    import eel
ModuleNotFoundError: No module named 'eel'
```

**Comment by aliparlakci** [comment]
Also, this is the console log of getting the requirements:
[requirements_log.txt](https://github.com/shadowmoose/RedditDownloader/files/2179162/requirements_log.txt)

**Comment by shadowmoose** [comment]
From a quick glance, it seems like pip isn't managing to install all the libraries you need. 

Try running ```pip install eel```, and see if it manages to install the library then.

**Comment by shadowmoose** [comment]
Ah, yes you did. I missed that on my mobile device.

This bit: 
```building 'lxml.etree' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools```

Indicates that pip is failing to build the lxml package one of RMD's libraries requires. This is likely breaking the installation procedure. I haven't personally run into this issue on my test machines. You'll need the Visual C++ Build Tools in order to build the package on your machine, or it may be possible to instead find a prebuilt wheel somewhere online.

**Comment by codedmon** [comment]
Hello @shadowmoose .   I am also recieving the error. 

The link provided in the script is old, so I installed the  'Microsoft Visual C++ Build Tools' using the install located here ->    https://visualstudio.microsoft.com/downloads/, selected 'Build Tools for Visual Studio 2017'.    I restarted my computer and I still get the error below.  Any suggestions?

```
running build_ext
    generating cffi module 'build\\temp.win32-3.7\\Release\\gevent.libuv._corecffi.c'
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    building 'gevent.libev.corecext' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

**Comment by shadowmoose** [comment]
Thanks for following up. I'll run a fresh install before the next release, and I'll be sure to document your additional steps.

**Comment by DinghyInstructor** [comment]
It seems I have a similar issue - I use Ubuntu 17.04, and had the following:- 
  Requirement already satisfied: gevent
  Requirement already satisfied: greenlet
and went on to say:-
  Successfully built eel bottle-websocket future
  Installing collected packages: bottle, gevent-websocket, bottle-websocket, future, whichcraft, eel
  Successfully installed bottle-0.12.16 bottle-websocket-0.2.9 eel-0.9.11 future-0.17.1 gevent-websocket-0.10.1 whichcraft-0.5.2
however, I too had my "import eel" instruction generate an "No module named 'eel'" error.
Any guidance on how to resolve this would be appreciated.
Please let me know if you require any additional details.
Many thanks,
