### ISSUE TITLE
Is there any way to run Reddit Media Downloader purely from the command line?

### ISSUE THREAD

**Issue by jonathanlaniado** [shadowmoose/RedditDownloader#43]
I want to be able to run this without opening the GUI. Is this possible?

When I run `python3 main.py -skip_pauses`, it appears I still have to click Start Downloading in the GUI.

**Comment by shadowmoose** [comment]
Yes, but it's not obvious. I need to get some time set aside to come back and touch up this project (it needs more obvious commands now that I've deprecated the old ones), but in the meantime you can start it headless by changing the setting in the command ```python main.py --interface.start_server=0```.

Also note that this will only work for launching the script as a one-off, and if you need to adjust settings you'll either have to edit the ```settings.json``` file directly, or configure it on a separate machine using the UI. If you absolutely need to configure the whole thing from scratch in a headless environment, download an older version and use the Wizard. I may bring the terminal-based config setup back, but it's currently deprecated.

I intend on making that command, as well as several others, more obvious. I'm finally at a point where I may have more free time to circle back to this project, and finally get the full UI version out as a stable release.
