### ISSUE TITLE
Filters created through the web gui are incorrect

### ISSUE THREAD

**Issue by eyriewow** [shadowmoose/RedditDownloader#44]
Hi,
I wanted to set up a few filters through the web gui but the filters created are wrong and result in no files getting downloaded (because they match no filter).

For example creating a "Title matches: 123" filter results in the creation of the following line in the settings.json:
`"title": "123"`

However, the line should read:
`"title.match": "123"` 

The same thing happens with score: minimum (results in "score": when it should be "score.min":) and I would assume other filters as well.

**Comment by shadowmoose** [comment]
Interesting. I must have broken something. 

Good catch. I'll take a look.

**Comment by shadowmoose** [comment]
This should be fixed as of 1272ccd7a02e4829b08b279894bd851a02026000.

Thanks again for the detailed report.
