### ISSUE TITLE
OFF TOPIC: Quick question.. about Twitter

### ISSUE THREAD

**Issue by EC-O-DE** [shadowmoose/RedditDownloader#45]
Quick question.. about Twitter - hope u don't mind?

Does anyone know similar app like this but for Twitter?

**Comment by shadowmoose** [comment]
Similar how? As in, a program like RMD that specifically downloads media from twitter feeds? Or are you wondering if RMD supports downloading Tweets linked to through Reddit?

I'm not familiar with anything similar to RMD for other social media, though I have been considering a few offshoots once I clean up the base platform a bit.

As for Reddit-linked Tweets, most media should be extracted properly.

**Comment by EC-O-DE** [comment]
Similar app just for Twitter feeds & content.

Only one that I have found is https://github.com/ScriptSmith/reaper

But I haven't set it up as it's not so straightforward as like RedditDownloader is. Or for example TumblThree.

**Comment by EC-O-DE** [comment]
So this has been second-best - but it doesn't have a memory :D :D 
https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

**Comment by shadowmoose** [comment]
Interesting. It's something I'll probably look into more in a while, once RMD 3.0 is (finally) released. I don't use either platform enough to know how straightforward a port of this project would be, but all the components for a generic threaded downloader are here.

**Comment by EC-O-DE** [comment]
TumblThree for Tumblr and https://github.com/MalloyDelacroix/DownloaderForReddit for Reddit and also your app for reddit. These are good.

**Comment by shadowmoose** [comment]
Interesting. I'm closing this issue for now, as it's not really RMD-specific, but I'll circle back to this when I have more time post-release.
