### ISSUE TITLE
All results are not shown

### ISSUE THREAD

**Issue by codedmon** [shadowmoose/RedditDownloader#47]
I am not getting all post when downloading.   According to Reddit Search page, the limitation of the search is 1000 results.s   RedditDownloader using the default Reddit search results?   If so, that explains why I am not getting all post downloaded.

**Comment by shadowmoose** [comment]
All Reddit resources are limited to the first 1000 results. This includes the posts provided through the API, which is what RMD uses. I unfortunately won't be able to bypass this limitation, as it is site-wide.

If the posts you are trying to download come from multiple subreddits, you can find more posts by individually downloading each sub. I'll try to add more filters and options to make this simpler, for those who need it.
