### ISSUE TITLE
i.redd.it files images not downloading

### ISSUE THREAD

**Issue by ShinyTile** [shadowmoose/RedditDownloader#49]
Hey there. Just wanted to double check: Is it me, or do images ULed to i.redd.it fail to download? I'm using the webui version and successfully getting downloads that are hosted on imgur, but not i.redd.it. Thank you!

**Comment by shadowmoose** [comment]
Thanks for the report. I haven't noticed any issues, but I'll specifically test for i.redd.it images and make sure they're working.

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
