### ISSUE TITLE
Authorize an Account doesn't do anything

### ISSUE THREAD

**Issue by commander-flatus** [shadowmoose/RedditDownloader#51]
Hi all. Fresh install on a Ubuntu 18.04 system. Erased my prior settings and manifest files.
On first run, the web interface opens up and I go to "settings" tab, then click on "Authorize an account" and nothing seems to happen. The account doesn't seem to authorize because subsequent downloading doesn't find anything to download.

Thanks.

**Comment by shadowmoose** [comment]
Clicking the Authorize button should open a browser window that leads to the Reddit account app authentication page. Are you perhaps blocking the popup in your browser?

**Comment by shadowmoose** [comment]
It's possible that the current method of opening an external window for auth is not currently working properly cross-platform, as it is a little strange. My guess is that some browsers are blocking this method of opening a window. I'll investigate other options to make this work more reliably.

**Comment by shadowmoose** [comment]
Should be resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.

**Comment by paul-hammant** [comment]
yay!
