### ISSUE TITLE
RMD backend keeps disconnecting

### ISSUE THREAD

**Issue by torchinz** [shadowmoose/RedditDownloader#52]
Hi. 
I have been really liking RMD. One particular issue, that I have been facing since the first time I used it, is that the browser integration or the WebUI, keeps on disconnecting (as shown in the attached screenshot). It becomes very difficult to add sources using webui as it keeps quitting on me. I don't think the port has anything to do with it. Currently, I have tweaked my settings file where I have kept the "keep it open" parameter as "true". But the UI is still quitting. I have tried downloading Chrome for the same but the same thing happens there too. I have tried changing browser from default and chrome but not to my help.
I hope you can show me what I maybe doing wrong here. Thank you. 
![issue-1](https://user-images.githubusercontent.com/17811608/51694747-7af1ef80-2027-11e9-96c3-f19a6e5299e1.png)

**Comment by shadowmoose** [comment]
Does it disconnect at any time, or just while actively downloading? There are a few bugs I need to work out, to prevent the backend from bogging down and disconnecting while the downloader is running.

**Comment by torchinz** [comment]
It disconnects within 10s of starting the main.py file (no downloading, nothing) and the downloading button of the UI does not work. So, I have to forcefully click "OK" and allow a restart. Once done, I have to be quick enough to click the "Start Downloading" button before it gets disconnected again. I am not sure what is creating this issue.

**Comment by torchinz** [comment]
Hi. I tried overwriting the manifest file in the download with a fresh one and the problem didn't appear anymore. Of course, RMD started downloading everything once again and I had to stop it, but it appears that the manifest file seems to be the one causing this issue. 
Hope this helps :)

**Comment by shadowmoose** [comment]
That's a very interesting find. I'll take a look. I think some of the threading may not be optimal for the timely serving of web content. 

My first guess is that the back-end may be bogging down when the UI is launched, and starts requesting downloaded media to preview. This is definitely a problem I'll have to fix. 

To get a better plan on replicating this, are you accessing RMD remotely?

**Comment by torchinz** [comment]
Hi. I am not accessing RMD remotely and yes, the WebUI cannot show the preview of the media downloaded. Surprisingly, I never mentioned that before but I had observed that. I try kept changing browser options, guessing that some of the add-ons might be blocking the media preview. However, I am getting an "Access Denied" 403 page when I click any media (broken) preview thumbnail. 
Maybe, when I tried with the new manifest file, the UI worked because it had no media to preview and loaded nicely. Is there a way, where I can disable the media preview option of the UI and see what happens?

**Comment by shadowmoose** [comment]
Yeah, I need to make some media preview changes soon. There's no good reason they should currently be loaded in the way they are. I'll work on improving this as soon as I can.

**Comment by SharingSpoon** [comment]
Hey

I'm getting this too when downloading. I don't see any preview thumbnails at all when downloading though

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
