### ISSUE TITLE
RMD is only downloading first page of user submitted posts

### ISSUE THREAD

**Issue by Eretsu** [shadowmoose/RedditDownloader#55]
I'm almost certain the post limit on Reddit is 1000, yet RMD only finds either 100 or 200 max source posts when downloading a user name.
![capture](https://user-images.githubusercontent.com/47490848/52754050-f8b57500-2fad-11e9-851f-2859267049ba.JPG)
![capture](https://user-images.githubusercontent.com/47490848/52545227-ab959100-2d6a-11e9-9a25-d130f0231b96.JPG)
There are no issues downloading a 1000 posts using other options. The "bug"(??) only occurs when using the "A User's Submission and/or Comment History" setting.
![capture 1](https://user-images.githubusercontent.com/47490848/52545239-c1a35180-2d6a-11e9-8e6f-7aa738e48e56.JPG)

**Comment by Eretsu** [comment]
Every user who has multiple pages of posts stop downloading at 99 items or less.

Example of 3 different users.
![capture 3](https://user-images.githubusercontent.com/47490848/52552466-34c1bd80-2d95-11e9-9da5-da676b9d8899.JPG)
![capture 4](https://user-images.githubusercontent.com/47490848/52552472-39867180-2d95-11e9-9f38-9c04398fa5fa.JPG)
![capture 2](https://user-images.githubusercontent.com/47490848/52552480-3e4b2580-2d95-11e9-8397-96da817867c0.JPG)

**Comment by shadowmoose** [comment]
Interesting bug - thanks for reporting it. I'll take a look.

**Comment by AndiKnight** [comment]
Can confirm this, I experience it myself 10 out of 10.

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
