### ISSUE TITLE
gfycat.com should use the youtube-dl handler to get the webm

### ISSUE THREAD

**Issue by den747** [shadowmoose/RedditDownloader#56]
Hi, first of thanks for your work, this is by far the best Reddit downloader.

At the moment gfycat.com links are getting downloaded as rather bad quality GIFs.

With youtube-dl it is possible to download the original .webm. It works directly with the non-hotlink links.

Example links:
https://gfycat.com/kindsardonicblesbok
https://giant.gfycat.com/KindSardonicBlesbok.webm

Greetings

**Comment by shadowmoose** [comment]
This is a good plan. I'll roll out a Handler to try and enforce the webm format for gfycat links.

**Comment by arujit** [comment]
Hi @shadowmoose. I have been playing around this project for a couple of days and I am really impressed by it. If it's possible I would like to contribute to this feature. Just checking if it's under development or something.

**Comment by shadowmoose** [comment]
@arujit Feel free to open a PR with this feature. I haven't had as much time as I'd like to work on this project over the last few months, so this change is not currently something I've looked at.

**Comment by arujit** [comment]
Sounds cool. Let me check youtube-dl. As I said currently have some time to spare, and am just playing around this project. I will try to add this feature. Or maybe I can contribute to other features as well.

**Comment by shadowmoose** [comment]
This feature, along with a little cleanup, has been added as of 93fafc587029f1948d9b3b178760b046331ac2ca.

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
