### ISSUE TITLE
Automated downloading

### ISSUE THREAD

**Issue by fluffyunic0rn** [shadowmoose/RedditDownloader#57]
Is it possible to check for new submissions in subreddits every x (adjustable) minutes and download those new submissions automatically? 

Thank you.

**Comment by shadowmoose** [comment]
Hey, the easiest way to manage this would be to scnedule RMD to run on a CRON (or any other task scheduler) job. Because there are a variety of much more developed methods to schedule tasks, RMD is unlikely to get support for scheduled scanning any time in the near future.

**Comment by fluffyunic0rn** [comment]
Sorry to bother you, but how would I go about scheduling RMD (v3.0) on a raspberry pi?

Thank you.

**Comment by shadowmoose** [comment]
I'd suggest a CRON job. You can find a Raspberry Pi example here: https://www.raspberrypi.org/documentation/linux/usage/cron.md

**Comment by fluffyunic0rn** [comment]
What would I execute with the cron job? Would executing /home/pi/RMD/main.py work?

Thank you.

**Comment by shadowmoose** [comment]
Without knowing your exact setup, you'll want to execute something like:
```python3 /home/pi/RMD/main.py --interface.start_server=false```
The parameter passed in will override the Settings file for the CRON execution, which will make sure the UI is not launched, and the the script will run without it.

__Also of note:__ You'll want to make sure the output's base directory (set in your ```settings.json```) is the absolute path to wherever you want the files stored.

To head off any other potential issues down the line, I'd suggest also hardcoding the settings file location in the command, like so:
```
python3 /home/pi/RMD/main.py --interface.start_server=false --settings="/home/abolute/path/to/settings.json"
```

This will prevent any issues with loading the correct settings configuration.

**Comment by trestlesky** [comment]
Hi, great work on the scripting. I'm trying to also find a solution to automate a daily run of a subreddit to catch all the submissions for that day. The above solution works to start the script headless, but when it's finished (only 12 downloads for today) it hangs indefinitely. I feel like I'm missing something easy. Is there a way to get the script to run, then close after it's done?
