### ISSUE TITLE
RMD not downloading posts >2000 in any subreddit

### ISSUE THREAD

**Issue by thehamzan6** [shadowmoose/RedditDownloader#59]
**Describe the bug**
RMD does not discover all posts in a subreddit, limiting to amounts between 1800-2000 posts, and doesn't find anymore posts.

**Environment Info (please complete the following information):**
 - **OS:** Archlinux
 - **RMD Version:** 3.0

**Comment by shadowmoose** [comment]
This is likely an issue with [PRAW](https://praw.readthedocs.io/en/v2.1.21/pages/faq.html#non-obvious-behavior-and-other-need-to-know), and more importantly, an issue with Reddit itself.

The Reddit API (and all other frontend Reddit sources) will only return up to ~1000 resources for any Sub/Comment chain/etc.

While I'd really love to solve this one, I don't think it's something that can be resolved. The limit is imposed server-side on Reddit. I'll look in to other alternatives when I can, but I'm not hopeful that there are any workarounds.

**Comment by shadowmoose** [comment]
Actually, never mind that previous post. I've implemented a new Source that can use PushShift to scrape entire Subreddits. See the commit d9ef1dbec24758bb5ab67a6e51cba208918129d3.

This will be available in the next RMD Release.
