### ISSUE TITLE
new ways to sort

### ISSUE THREAD

**Issue by mechgod1** [shadowmoose/RedditDownloader#62]
One of my sources is a user's submissions. The downloads are sorted based on the subreddit they were posted to. The ability to sort these into a separate folder would be cool.

For example if my source is u/tom and he posts in subreddits r/gaming and r/math, then his posts would be divided into the two folders gaming and math. Is it feasible to store all of his posts into a separate folder titled tom?

Thanks in advance

**Comment by shadowmoose** [comment]
Yes, RMD can group the files into any directory pattern you would like. You simply have to edit the file output patterns in the settings file. The output patterns support embedding data (such as the author's username, the subreddit, etc) directly into the file path.

In this case, you'd want the file directory path to look something like: ```/custom_dir_name/[user]/```.
The new (upcoming) release will condense the setting's "file_pattern" and "subdir_pattern" into one single pattern, so if you're running unreleased versions, make sure to edit accordingly.

**Comment by mechgod1** [comment]
thanks for the help im a noob at this i appreciate it

**Comment by shadowmoose** [comment]
You're correct, it should be ```[author]```. Good catch.

Feel free to ask if you have any more questions, otherwise I'm closing this issue for now.
