### ISSUE TITLE
Downloader Hangs up

### ISSUE THREAD

**Issue by arujit** [shadowmoose/RedditDownloader#65]
**Unable to Download**
- After prompting the web UI and completing authentication(Settings-> Change Authorized Account), I pressed the **Start Download** button. But Downloader hangs up after that.
- And I am not able to browse anything in the Browse page.
(Home Screen now)
![image](https://user-images.githubusercontent.com/16621282/64368611-525bba80-d038-11e9-8d97-54638609c5f6.png)

**Environment Info **
 - **OS:** [Mac]
 - **RMD Version:** [3.0.0]

**Screenshots/Information**
- logs 
![image](https://user-images.githubusercontent.com/16621282/64368818-aff00700-d038-11e9-818c-6699b9f0aaaa.png)

**Additional context**
- After debugging, I found there is some issue with logging in to reddit(Basically I am getting None user in login function of `praw_warpper.py` file). Am I missing something? All the credentials seem fine to me.

**Suggestions**
- The docs seem deprecated. Please update them and I think there should be the wizard mode as before(As I was looking for some reddit media cli and yeah its a feature request).

**Comment by shadowmoose** [comment]
It looks like you're running into some macOS thread-related security thing, preventing RMD from starting processes to manage the downloading.

I don't have a Mac myself, but I'll try to roll out an osx test environment soon.

In the meantime, you can try the fix proposed here: https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

**Comment by arujit** [comment]
Really appreciate the help. Will try to fix it. :)

**Comment by shadowmoose** [comment]
As a small update, I've enabled testing on all major platforms through GitHub Actions.

It looks like RMD runs fine on the latest macOS version, so I think your problem is related to the link I posted earlier.

**Comment by shadowmoose** [comment]
I'm closing this, because my testing shows everything should be working on macOS. Feel free to re-open if it's still not working.

Also, I've added more documentation - [actually a whole new documentation site](https://shadowmoose.github.io/RedditDownloader/) - to help with configuration.
