### ISSUE TITLE
pip install -r requirements.txt throws an error

### ISSUE THREAD

**Issue by Cryptoloops** [shadowmoose/RedditDownloader#67]
I'm using linux and admittedly I am a noob.
I get the following error message when trying to install RMD:

```
Collecting psaw (from -r requirements.txt (line 1))
  ERROR: Could not find a version that satisfies the requirement psaw (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for psaw (from -r requirements.txt (line 1))

```

**Comment by shadowmoose** [comment]
Hello, in order to diagnose this issue, I'm going to need to know your Python and Linux versions. Specifically, the Python version can be found by running ```python -V``` in your terminal.

**Comment by Cryptoloops** [comment]
Im running the latest kali linux. 

Doing python —version gives me 2.7.16
Python3 —version gives me 3.7.4

**Comment by shadowmoose** [comment]
Are you sure you're using Py3 for the install? Python3 should be able to install all the requirements, but python2 is not supported.

**Comment by Cryptoloops** [comment]
I found the issue. Python 2 and 3 are installed simultaneously. I had to uses pip3 instead of pip.
