### ISSUE TITLE
It seems my redditdownloader is only downloading like 10 posts per 1000 in queue.

### ISSUE THREAD

**Issue by dangledoodles** [shadowmoose/RedditDownloader#68]
I just finished downloading the first 1000 after taking so long to get it all setup. (im a completely useless when it comes to stuff like this) anyway i went to run it again because i have a shit ton of things saved and it loads all my saved posts and starts downloading with 5 threads as default. but then only one of the handler's is actually downloading things. so it quickly blasts through all the 1000 in queue and then finishes with only like 10 things downloaded? if that makes sense. Also while im here, how the hell do you get the webui setup

**Comment by dangledoodles** [comment]
after further testing it seems that after the first 1000ish posts deleted it seems to not download anymore, is this a issue with reddit? i probably have like 5000+ posts saved

**Comment by dangledoodles** [comment]
Never mind even more, just read some of the other issue threads and saw your comment about reddit limiting the program to 1000 posts

**Comment by shadowmoose** [comment]
Yes, unfortunately the built0-in limitations to Reddit apply everywhere, so there is no way around them for personal liked/saved posts. 

If you're trying to get more posts from public sources, such as subreddits, the PushShift Sources support unlimited. PushShift doesn't have access to your liked/saved posts though, sadly.
