### ISSUE TITLE
Unable to launch after installing

### ISSUE THREAD

**Issue by squiglybob13** [shadowmoose/RedditDownloader#75]
I install python and ran the script in install dependencies. But when I try to run `python redditdownloader`, it gives an error: `python: can't open file 'redditdownloader': [Errno 2] No such file or directory`.

- Windows 10 Education 1903
- RMD Version: 3.0.0

[Screenshot](https://puu.sh/Epv4b/32b260d829.png)

**Comment by squiglybob13** [comment]
Sorry for the late follow up. I ran it from the folder but no result. Here is a screenshot of the redditdownloader folder:

![0609cc6038 1](https://user-images.githubusercontent.com/502576/67030341-0e8eb300-f0c4-11e9-8fe6-96292122bfb1.png)

**Comment by shadowmoose** [comment]
If you launch the ```main.py``` file, is RMD able to start?

**Comment by wigsnes** [comment]
I had the same problem where I could not start redditdownloader
`...\python.exe: can't open file 'redditdownloader': [Errno 2] No such file or directory`
I managed to start `main.py` and ran trough the setup, next run `main.py` again to start downloading. Might be a goo idea to add this as a second way of use, in the instructions.

**Comment by squiglybob13** [comment]
I'll give that a try when I get home tonight. Been busy with midterms so
haven't had time to mess with it lol

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
