### ISSUE TITLE
Feature request: ability to see failed links in a list

### ISSUE THREAD

**Issue by undertheblu3sky** [shadowmoose/RedditDownloader#76]
I'd love to see the ability to be able to see links that either fail or even skipped.

For example if RMD doesn't find a imgur link but is a legit link, I still have a chance to manually download it.

**Comment by shadowmoose** [comment]
I like this idea. It would be nice to add this to the UI.

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
