### ISSUE TITLE
The relative path cannot elevate above the Base Parent

### ISSUE THREAD

**Issue by cgibbons87** [shadowmoose/RedditDownloader#85]
Hi. I'm having a hard time installing RMD 3.0.0. I have version 2.01 working fine. This is on Win10.

So, I extracted the zip file, checked and updated my dependencies manually and ran 'py Run.py' from the RedditDownloader-master dir.

The output is "The relative path cannot elevate above the Base Parent"

This seems to be generated by lines 26 and 27 in rel_file.py.
  
When I insert print statements for base and join_test before these lines I get the following output right before the error.

"
C:\Users\Christopher\Desktop\RedditDownloader-master\download
C:\Users\Christopher\Desktop\RedditDownloader-master\download\manifest.sqlite
"

When I comment out the lines triggering the error, the program runs, but when the WebUI tries to load it gives me a 403 error.

### Environment Info
 - **OS: Windows 10** 
 - **RMD Version: 3.0.0**

**Comment by shadowmoose** [comment]
Interesting, that error means that RMD is trying to build a file path that points outside the base save directory. The ```rel_file.py``` library is a wrapper to - among other things - help prevent that exact issue from happening. It's strange to see it so early in startup.

Is there a larger stack trace you can post? Unfortunately, I'm not able to see what piece of code is raising this issue.

**Comment by cgibbons87** [comment]
![error](https://user-images.githubusercontent.com/48956104/68221996-4fd5fc80-ffb8-11e9-8a5d-2cf53139f32f.png)

I think I found out what the issue was. The default settings.json gives a base dir that ends with a forward slash. 

When I remove it the error no longer comes up.

![Capture](https://user-images.githubusercontent.com/48956104/68223726-5023c700-ffbb-11e9-827a-372ca33a52a3.JPG)

Must be some strange windows-related thing.

Oddly enough, the 403 error still comes up.

![403](https://user-images.githubusercontent.com/48956104/68222779-8bbd9180-ffb9-11e9-9637-0f25074b7fe8.JPG)

I've tried shutting down the firewall, changing ports, and running as an admin. No luck.

**Comment by shadowmoose** [comment]
Thanks for posting those extra details. That trailing directory slash was unintended, but shouldn't have been causing an issue with Windows paths. Either way, I've rolled out a fix, which also contains better error logging.

The http 403 response is odd. I'm not able to replicate it mysel, though it does appear to be coming from RMD's webserver library. 

Since you've tried switching ports, have you made sure RMD can access the install directory it is in? It needs to have read access to all the files within the ```web``` directory.

**Comment by cgibbons87** [comment]
Thanks.

I'm afraid nothing I've tried has fixed the 403 issue. I've alternately tried running RMD and the browser as an admin, putting it in different directories (including privileged ones), and shutting down everything else on my system that is even vaguely networking related. No luck. 

Is it still possible to run RMD without the GUI? I've tried copy/pasting the authentication section from the 2.01 config file into the 3.0.0 file and nothing is downloaded (though there are no errors).

**Comment by shadowmoose** [comment]
I'm still not sure what could be causing that issue, but it is certainly possible to run RMD without the UI. 

You actually just reminded me that I'd forgotten to add authentication support to the console interface, so as of 8c0b28691d75b54c3407ae2fad40dfed467b5681 that's been added. 

You simply need to run RMD with the ```--authorize``` flag, and follow the prompts.

**Comment by cgibbons87** [comment]
Excellent. I suppose my system might be weird somehow regarding the 403 error. But the command line suits me just fine. However, another error comes up when I try to run with --authorize

![Capture](https://user-images.githubusercontent.com/48956104/68383462-b592c780-0123-11ea-9e85-642164cb65f6.PNG)

Sorry to keep bothering you.

**Comment by shadowmoose** [comment]
Oops, I missed that in testing. Fixed as of 80017fe44e9b555b0591933f7237e86345387bde.

It occurs to me now that adding new Sources directly to the settings JSON is likely too tricky for anybody to do without using the UI or manually reading the Source's Python code. I'll have to roll up a console-based Source editor soon.

In the meantime, if you want to download more than the default liked+saved Posts, and if you don't mind manually editing the `settings.json` `sources` field, [here's a list of all possible sources + demo filters you can mix & match](https://gist.github.com/shadowmoose/dbe17f26e112b832a6eec8ed68cb71fb). You can have duplicate source types, they just need to have unique `alias` values.

**Comment by cgibbons87** [comment]
Ah, it's working now. Thank you!

**Comment by shadowmoose** [comment]
Excellent! Feel free to let me know if you run into any other problems.
