### ISSUE TITLE
RMD 3.0 not available?

### ISSUE THREAD

**Issue by Saortica** [shadowmoose/RedditDownloader#86]
My apologies if I am just missing something very obvious (new to github).

But I can't see a way to currently download version 3.0? Latest version for me is listed as 2.1.

I see mentions to a legacy-3.0, perhaps you retired it for the moment?

For the moment I might try using 2.1, but am at a bit of a disadvantage as the documentation pages seem to refer to the WebGUI in 3.0.

Cheers!

**Comment by shadowmoose** [comment]
Hey, sorry, I should have made that more clear.
RMD 3.0.0 is currently in development, and I had intended to release it a while ago. However, a few bug reports have popped up that have stalled that release. The online documentation was set up in advance, but I would have held off if I'd realized there would be a delay.

In the meantime, you can either download RMD from the ``master``` branch and use the online documentation, or you can find the 2.x docs locally inside the downloaded project directory.

One way or another, I think I'll be pushing for a release this week. Teasing shows that 3.0.0 is stable in most use cases, on all major platforms.

**Comment by Saortica** [comment]
Awesome, thanks for clearing that up. I'll look forward to having a go at 3.0.0.
