### ISSUE TITLE
RMD fatal error

### ISSUE THREAD

**Issue by Dagon330** [shadowmoose/RedditDownloader#99]
I have got this problem. Error ocur when the app stops working and i trana restart it. 

https://imgur.com/HKv6Nn3

I don't do programing so i just wanna clear answear for a dummy. And can i get  some tutorial how to use it. I read the tutorial on site but i do smh wrong and nothing work.

**Comment by shadowmoose** [comment]
Hello, is this a fresh RMD install? Has it been run on your system before this error?

**Comment by Dagon330** [comment]
I run it once or twice. PC restart didn't help.

**Comment by shadowmoose** [comment]
It looks like the manifest it generated became malformed somehow. 

If you haven't downloaded anything yet, can you try deleting the SQLite file RMD generated in the output folder.

**Comment by Dagon330** [comment]
OK i did it. It lauches. Still don't work. I follow step by step, authorise an account and made everything like it should be but it dowloads nothing. I have subreddit put in sources. I use "the submissions in one or more subreddits" and i put "r/memes" in the subreddit thing. It seems like it doesn't detect anything. Can you help me? I was using your guide that is linked in application. Maybe  i have smh configure wrong?

**Comment by Dagon330** [comment]
Offf, i accidentally closed it, sorry.

**Comment by NandaKumar8776** [comment]
hey i have the same problem, where is the output folder for sqlite? how do you solve the problem? i was able to run it once but then the second time i got the same error message.

**Comment by shadowmoose** [comment]
Odd, you also hadn't run any previous versions of RMD? What system are you running on?

The output folder is, by default, in the `download` directory wherever you launch RMD.

**Comment by shadowmoose** [comment]
Closing this issue and tying ot into #104, since they seem to be the same.
